// SPDX-License-Identifier: LicenseRef-PolyForm-Noncommercial-1.0.0
// Copyright (c) 2026 Alonso J. Núñez (GS·RUN)

#include "export/slangp_exporter.h"

#include "core/pipeline.h"

#include <fstream>
#include <sstream>

namespace tubelight::exporter {

namespace {

// Maps Tubelight's internal mask_type integer (matches GlobalParams::mask_type
// in core/pipeline.h) to a human-friendly parameter value.
int mask_type_for_export(MaskType m) {
    switch (m) {
        case MaskType::None:           return 0;
        case MaskType::Shadow:         return 1;
        case MaskType::ApertureGrille: return 2;
        case MaskType::Slot:           return 3;
        case MaskType::Diamond:        return 4;
        case MaskType::CgwgMix:        return 5;
        case MaskType::DotTrio:        return 6;
    }
    return 1;
}

} // namespace

bool export_slangp(const CRTProfile& crt,
                   const SignalProfile& signal,
                   const std::string& output_path,
                   std::string& error_out) {
    std::ofstream out(output_path);
    if (!out.is_open()) {
        error_out = "cannot open output file: " + output_path;
        return false;
    }

    // The .slangp format lists shader passes with paths and per-pass
    // parameters. We emit one shader per Tubelight pass and a set of
    // parameters derived from the profile.

    out << "# Generated by Tubelight v0.1.0 — DO NOT EDIT by hand.\n";
    out << "# Source profile: " << crt.id << "\n";
    out << "# Source signal:  " << signal.id << "\n\n";

    constexpr const char* kShaderFilenames[8] = {
        "pass_minus1_signal.glsl",
        "pass0_analysis.glsl",
        "pass1_dither_reconstruct.glsl",
        "pass2_beam_scanlines.glsl",
        "pass3_mask.glsl",
        "pass4_bloom.glsl",
        "pass5_temporal.glsl",
        "pass6_composition.glsl"
    };

    out << "shaders = 8\n";
    for (int i = 0; i < 8; ++i) {
        out << "shader" << i << " = shaders/tubelight/" << kShaderFilenames[i] << "\n";
        out << "filter_linear" << i << " = true\n";
        out << "wrap_mode" << i << " = clamp_to_edge\n";
        out << "scale_type" << i << " = source\n";
        out << "scale" << i << " = 1.0\n";
        out << "float_framebuffer" << i << " = true\n";
        out << "\n";
    }

    // Parameter block (RetroArch reads these as #pragma parameter values in
    // the shader source; we replicate them here for documentation).
    out << "# Tubelight profile-derived parameters\n";
    out << "parameters = \"scanline_strength;mask_type;mask_pitch_px;"
        << "luma_mhz;chroma_i_mhz;chroma_q_mhz;dot_crawl_strength;"
        << "ringing_amount;noise_strength;barrel_strength;vignette_strength\"\n";

    auto p = [&](const char* k, double v) {
        out << k << " = \"" << v << "\"\n";
    };
    p("scanline_strength",   crt.scanline_strength);
    p("mask_type",           mask_type_for_export(crt.mask_type));
    p("mask_pitch_px",       (crt.dot_pitch_mm.has_value() ? crt.dot_pitch_mm.value() : 0.4) * 4.5);
    p("luma_mhz",            signal.luma_mhz);
    p("chroma_i_mhz",        signal.chroma_i_mhz);
    p("chroma_q_mhz",        signal.chroma_q_mhz);
    p("dot_crawl_strength",  signal.dot_crawl_strength);
    p("ringing_amount",      signal.ringing_amount);
    p("noise_strength",      signal.noise_strength);
    p("barrel_strength",     0.06);
    p("vignette_strength",   0.35);

    out << "\n";
    out << "# To use this preset in RetroArch:\n";
    out << "#   1. Copy this file to <retroarch_assets>/shaders/tubelight/\n";
    out << "#   2. Copy Tubelight's shaders/*.frag to the same dir, renamed *.glsl\n";
    out << "#   3. RetroArch menu: Settings > Shaders > Load Preset\n";

    return true;
}

} // namespace tubelight::exporter
